#!/bin/sh

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway
export XDG_MENU_PREFIX=plasma-

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# set default dir for grim
export GRIM_DEFAULT_DIR="$HOME/Pictures/Screenshots" 

exec systemd-cat --identifier=sway sway "$@"
